# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
    
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm install
    - run: npm run-script build
    - run: cp /home/runner/work/WBLayout/WBLayout/style.css /home/runner/work/WBLayout/WBLayout/dist/
    
    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: /home/runner/work/WBLayout/WBLayout/dist
        
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
